name: ARM64

on:
  # run every day of the week at 02:00
  schedule:
    - cron: 0 2 * * *

jobs:
 build-arm64-docker:
  name: Build for ARM64 on Docker
  runs-on: ubuntu-20.04
  if: (github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')) || github.event_name == 'schedule' # tag or schedule
  steps:
    - name: Install docker # bug in ubuntu, conflicts with docker.io
      run: |
        sudo apt-get update
        sudo apt-get remove --purge -y moby-engine moby-cli
        sudo apt-get install -y qemu-user-static docker.io

    - uses: actions/checkout@v2

    - name: ARM64 build
      run: |
        sudo docker build -t htm-arm64-docker --build-arg arch=arm64 .

    - name: Tests
      run: |
        sudo docker run htm-arm64-docker python setup.py test

    - name: Copy files from docker
      run: |
        sudo docker cp `sudo docker ps -alq`:/usr/local/src/htm.core/dist dist #TODO the `command` is not 100% reliable, replace with some name/id
        ls dist
